package personabuilder

import (
	"os"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/vipulvpatil/candidate-tracker-go/internal/clients/openai"
	"github.com/vipulvpatil/candidate-tracker-go/internal/model"
)

func Test_BuildSuccess(t *testing.T) {
	t.Run("run examples", func(t *testing.T) {
		fileContent, err := os.ReadFile("persona_testcase_inputs.txt")
		assert.NoError(t, err)

		testInputs := strings.Split(string(fileContent), "***")
		testExpectedOutputs := []*model.Persona{
			{Name: "First Last", Email: "first.last@example.com", Phone: "+91 1234567890", City: "", State: "", Country: "", YoE: 7, TechSkills: []string{"React JS", "React Native", "TypeScript", "Next JS", "Graphql"}, SoftSkills: []string{}, RecommendedRoles: []string{"Software Engineer", "Senior Software Engineer", "Product Engineer"}, Education: []model.Education{{Institute: "Dehradun Institute of Technology", Qualification: "Bachelor of Technology", CompletionYear: "2016"}}, Experience: []model.Experience{{Title: "Senior Software Engineer", CompanyName: "Coinbase", StartingYear: "2021", EndingYear: "", Ongoing: true}, {Title: "Software Engineer II", CompanyName: "Microsoft", StartingYear: "2020", EndingYear: "2021", Ongoing: false}, {Title: "Product Engineer", CompanyName: "GoJek", StartingYear: "2019", EndingYear: "2020", Ongoing: false}, {Title: "Senior Software Engineer", CompanyName: "Paytm Smart Retail", StartingYear: "2018", EndingYear: "2019", Ongoing: false}, {Title: "Lead Front End Developer", CompanyName: "Designbids Technologies Pvt. Ltd.", StartingYear: "2016", EndingYear: "2018", Ongoing: false}, {Title: "Front End Developer", CompanyName: "Vaidik Technologies Pvt. Ltd.", StartingYear: "2015", EndingYear: "2016", Ongoing: false}}, Certifications: []string{}, BuilderVersion: "1.0.0", BuiltBy: "AI", FileUploadId: ""},
			{Name: "First Last", Email: "first.last@example.com", Phone: "+91 1234567890", City: "Bangalore", State: "Karnataka", Country: "India", YoE: 11, TechSkills: []string{"Brand Development", "Marketing Strategy", "Product Launch", "Digital Marketing", "Campaign Management"}, SoftSkills: []string{"Leadership", "Team Management", "Strategic Planning", "Communication", "Problem Solving"}, RecommendedRoles: []string{"Chief Marketing Officer", "Brand Manager", "Marketing Director"}, Education: []model.Education{{Institute: "Mudra Institute of Communications", Qualification: "PGDM(C)", CompletionYear: "2013"}, {Institute: "Mumbai University", Qualification: "B.E. (Electronics)", CompletionYear: "2009"}}, Experience: []model.Experience{{Title: "Chief Business Officer", CompanyName: "", StartingYear: "", EndingYear: "", Ongoing: true}, {Title: "Manager, Marketing", CompanyName: "", StartingYear: "", EndingYear: "", Ongoing: false}, {Title: "Senior Marketing Manager", CompanyName: "", StartingYear: "", EndingYear: "", Ongoing: false}, {Title: "Marketing Manager", CompanyName: "", StartingYear: "", EndingYear: "", Ongoing: false}, {Title: "Sr. Site Merchandizer", CompanyName: "", StartingYear: "", EndingYear: "", Ongoing: false}, {Title: "Site Merchandizer", CompanyName: "", StartingYear: "", EndingYear: "", Ongoing: false}, {Title: "Assistant Project Manager", CompanyName: "", StartingYear: "", EndingYear: "", Ongoing: false}}, Certifications: []string{}, BuilderVersion: "1.0.0", BuiltBy: "AI", FileUploadId: ""},
			{Name: "First Last", Email: "first.last@example.com", Phone: "+91 1234567890", City: "Trivandrum", State: "Kerala", Country: "India", YoE: 4, TechSkills: []string{"C", "C++", "Java", "Python", "Go"}, SoftSkills: []string{}, RecommendedRoles: []string{"Software Engineer", "Full Stack Developer", "Cloud Engineer"}, Education: []model.Education{{Institute: "College of Engineering Trivandrum", Qualification: "B.Tech in Computer Science", CompletionYear: "2019"}, {Institute: "Silver Hills Higher Secondary School", Qualification: "Higher Secondary Education", CompletionYear: "2015"}}, Experience: []model.Experience{{Title: "Software Engineer II (L4)", CompanyName: "Uber", StartingYear: "Sept 2022", EndingYear: "Present", Ongoing: true}, {Title: "Software Engineer (IC4)", CompanyName: "Coinbase", StartingYear: "Oct 2021", EndingYear: "Sept 2022", Ongoing: false}, {Title: "Software Development Engineer - II", CompanyName: "Amazon", StartingYear: "July 2019", EndingYear: "Oct 2021", Ongoing: false}, {Title: "Research Intern", CompanyName: "IIT Madras", StartingYear: "May 2018", EndingYear: "July 2018", Ongoing: false}}, Certifications: []string{"AWS Certified Solutions Architect Associate", "Hashicorp Certified Terraform Associate"}, BuilderVersion: "1.0.0", BuiltBy: "AI", FileUploadId: ""},
			{Name: "First Last", Email: "first.last@example.com", Phone: "+91 1234567890", City: "Thane", State: "Maharashtra", Country: "India", YoE: 10, TechSkills: []string{"AutoCAD 2D", "MS Office", "SketchUp 3D", "Photoshop", "Revit"}, SoftSkills: []string{"Communication", "Client Relationship", "Project Management", "Team Collaboration", "Creativity"}, RecommendedRoles: []string{"Senior Architect", "Junior Architect", "Intern"}, Education: []model.Education{{Institute: "Bharati Vidyapeeth College Of Architecture, Kharghar", Qualification: "BACHELOR OF ARCHITECTURE", CompletionYear: "2012"}, {Institute: "South Indian Education Society, Sion", Qualification: "HIGHER SECONDARY CERTIFICATE", CompletionYear: "2004"}, {Institute: "St.John The Baptist High School, Thane", Qualification: "SECONDARY SCHOOL CERTIFICATE", CompletionYear: "2002"}}, Experience: []model.Experience{{Title: "Senior Architect", CompanyName: "SAAKAAR ARCHITECTS", StartingYear: "Feb' 2018", EndingYear: "", Ongoing: true}, {Title: "Junior Architect", CompanyName: "DA DESIGNS", StartingYear: "July' 2012", EndingYear: "Jan' 2018", Ongoing: false}, {Title: "Intern", CompanyName: "ARCHITECTS COLLABORATION", StartingYear: "Oct' 2011", EndingYear: "Jan' 2012", Ongoing: false}}, Certifications: []string{}, BuilderVersion: "1.0.0", BuiltBy: "AI", FileUploadId: ""},
			{Name: "First Last", Email: "first.last@example.com", Phone: "+91 1234567890", City: "Navi Mumbai", State: "", Country: "India", YoE: 10, TechSkills: []string{"Financial Accounting", "Taxation", "Planning", "Reporting", "ERP"}, SoftSkills: []string{"Strategic Thinking", "Problem Solving", "Data Analysis", "Communication", "Attention to Detail"}, RecommendedRoles: []string{"Cost & Management Accountant", "Financial Analyst", "Tax Consultant"}, Education: []model.Education{{Institute: "", Qualification: "CMA", CompletionYear: "2010"}, {Institute: "", Qualification: "M.Com (Costing)", CompletionYear: "2011"}, {Institute: "", Qualification: "B.Com (Accounts and Finance)", CompletionYear: "2005"}, {Institute: "", Qualification: "HSC", CompletionYear: "2002"}, {Institute: "", Qualification: "SSC", CompletionYear: "2000"}}, Experience: []model.Experience{{Title: "Manager Accounts & Finance", CompanyName: "Neural Integrated Systems Pvt. Ltd", StartingYear: "July 2019", EndingYear: "Present", Ongoing: true}, {Title: "Manager Accounts & Finance", CompanyName: "Neural Integrated Systems Pvt. Ltd", StartingYear: "May 2012", EndingYear: "April 2015", Ongoing: false}, {Title: "Senior Accountant", CompanyName: "Dhruvi Foods and Beverages Ltd", StartingYear: "December 2011", EndingYear: "April 2012", Ongoing: false}, {Title: "Accountant", CompanyName: "Ravindra Watwe & Associates", StartingYear: "March 2010", EndingYear: "April 2011", Ongoing: false}, {Title: "Assistant Accountant", CompanyName: "Children Future India", StartingYear: "January 2008", EndingYear: "April 2009", Ongoing: false}, {Title: "Assistant Accountant", CompanyName: "Tax consultancy firm", StartingYear: "June 2007", EndingYear: "December 2007", Ongoing: false}}, Certifications: []string{"CMA (ICWAI)", "M.Com (Costing)"}, BuilderVersion: "1.0.0", BuiltBy: "AI", FileUploadId: ""},
			{Name: "First Last", Email: "first.last@example.com", Phone: "+91 1234567890", City: "San Francisco", State: "California", Country: "United States", YoE: 13, TechSkills: []string{"AWS", "Javascript", "TypeScript", "NodeJS", "ReactJS"}, SoftSkills: []string{"Team Management", "Technical Leadership", "Hiring", "Sprint Planning", "Scrum"}, RecommendedRoles: []string{"Software Engineering Manager", "Full Stack Engineer", "Technical Lead"}, Education: []model.Education{{Institute: "", Qualification: "Masters in Computer Science", CompletionYear: "December 2010"}, {Institute: "", Qualification: "Bachelors in Computer Engineering", CompletionYear: "July 2008"}}, Experience: []model.Experience{{Title: "Software Development Manager", CompanyName: "Amazon Web Services", StartingYear: "Feb' 2022", EndingYear: "", Ongoing: true}, {Title: "Engineering Manager", CompanyName: "Zillow Premier Agent", StartingYear: "Feb' 2020", EndingYear: "Feb' 2022", Ongoing: false}, {Title: "Senior Software Engineer - Full Stack", CompanyName: "Zillow Premier Agent", StartingYear: "Jun' 2018", EndingYear: "Feb' 2020", Ongoing: false}, {Title: "Software Engineer - Full Stack", CompanyName: "Spruce Finance", StartingYear: "June' 2013", EndingYear: "May 2018", Ongoing: false}, {Title: "Founder", CompanyName: "Beep", StartingYear: "Mar’ 2017", EndingYear: "Jun' 2019", Ongoing: false}, {Title: "Founding Engineer", CompanyName: "Izelis corp", StartingYear: "Mar’ 2011", EndingYear: "Feb' 2012", Ongoing: false}, {Title: "Software Engineer - Platform", CompanyName: "Gaia Interactive", StartingYear: "Feb’ 2012", EndingYear: "Jun' 2013", Ongoing: false}}, Certifications: []string{}, BuilderVersion: "1.0.0", BuiltBy: "AI", FileUploadId: ""},
			{Name: "First Last", Email: "first.last@example.com", Phone: "+91 1234567890", City: "San Francisco", State: "CA", Country: "USA", YoE: 10, TechSkills: []string{"Cardiopulmonary Physical Therapy", "Orthopedic Physical Therapy", "Clinical Solutions", "Manual Therapy", "Electrotherapy"}, SoftSkills: []string{"Team Player", "Management", "Communication", "Leadership", "Multidisciplinary Collaboration"}, RecommendedRoles: []string{"Cardiopulmonary Physical Therapist", "Orthopedic Physical Therapist", "Rehabilitation Program Director"}, Education: []model.Education{{Institute: "Arcadia University, Pennsylvania", Qualification: "Doctorate of Physical Therapy", CompletionYear: "2021"}, {Institute: "San Francisco State University, San Francisco", Qualification: "MSc Kinesiology", CompletionYear: "2011"}, {Institute: "Laxmi Memorial College, India", Qualification: "BSc Physiotherapy", CompletionYear: "2008"}}, Experience: []model.Experience{{Title: "Rehabilitation Program Director", CompanyName: "", StartingYear: "", EndingYear: "", Ongoing: true}, {Title: "Physical therapist", CompanyName: "", StartingYear: "", EndingYear: "", Ongoing: false}, {Title: "Physical therapist", CompanyName: "", StartingYear: "", EndingYear: "", Ongoing: false}, {Title: "Physical therapist", CompanyName: "", StartingYear: "", EndingYear: "", Ongoing: false}, {Title: "Physical therapist", CompanyName: "", StartingYear: "", EndingYear: "", Ongoing: false}}, Certifications: []string{"CPR certified", "Spine, Elbow & Ankle Manipulation", "Diploma in Yoga Therapy", "Balance training and Swiss ball Thera"}, BuilderVersion: "1.0.0", BuiltBy: "AI", FileUploadId: ""},
			{Name: "First Last", Email: "first.last@example.com", Phone: "+91 1234567890", City: "", State: "", Country: "", YoE: 12, TechSkills: []string{"Business Development", "Account Management", "Revenue Maximization", "Marketing Strategy", "Advertising"}, SoftSkills: []string{"Client Relationship Management", "Negotiation", "Strategic Thinking", "Leadership", "Communication"}, RecommendedRoles: []string{"Business Development Manager", "Key Account Manager", "Senior Marketing Manager"}, Education: []model.Education{{Institute: "VIT (Wadala), University of Mumbai", Qualification: "MMS, Marketing Management", CompletionYear: "2011"}, {Institute: "Vivekanand Education Society’s Institute of Technology", Qualification: "B.E., Engineering", CompletionYear: "2008"}, {Institute: "St. John the Baptist Junior College, University of Maharashtra", Qualification: "H.S.C", CompletionYear: "N/A"}, {Institute: "St. John the Baptist High School", Qualification: "SSC", CompletionYear: "N/A"}}, Experience: []model.Experience{{Title: "Biz Dev Manager", CompanyName: "", StartingYear: "", EndingYear: "", Ongoing: true}, {Title: "Senior Manager (KAM, FTA Genre)", CompanyName: "", StartingYear: "", EndingYear: "", Ongoing: false}, {Title: "Senior Manager (Zee Marathi)", CompanyName: "", StartingYear: "", EndingYear: "", Ongoing: false}, {Title: "Sr. Executive (WEST FMCG accounts)", CompanyName: "", StartingYear: "", EndingYear: "", Ongoing: false}, {Title: "Deputy Manager", CompanyName: "", StartingYear: "", EndingYear: "", Ongoing: false}, {Title: "Sr. Officer", CompanyName: "", StartingYear: "", EndingYear: "", Ongoing: false}, {Title: "Marketing Exec.", CompanyName: "", StartingYear: "", EndingYear: "", Ongoing: false}}, Certifications: []string(nil), BuilderVersion: "1.0.0", BuiltBy: "AI", FileUploadId: ""},
			{Name: "First Last", Email: "first.last@example.com", Phone: "+91 1234567890", City: "Mumbai", State: "Maharashtra", Country: "India", YoE: 14, TechSkills: []string{"Delphi 6", "C#", "Elixir", "Azure DevOps", "Javascript"}, SoftSkills: []string{"Team player", "Problem solving", "Communication", "Leadership", "Agile/Scrum"}, RecommendedRoles: []string{"Solution Architect", "Technical Specialist", "Manager"}, Education: []model.Education{{Institute: "Konkan Gyanpeeth College Of Engineering", Qualification: "Bachelor's Degree in Information Technology (Data Warehousing and Mining)", CompletionYear: "2008"}, {Institute: "Distance Open Learning (Mumbai University)", Qualification: "Master in Information Technology", CompletionYear: "Ongoing"}}, Experience: []model.Experience{{Title: "Solution Architect", CompanyName: "", StartingYear: "", EndingYear: "", Ongoing: true}, {Title: "Technical Specialist", CompanyName: "", StartingYear: "", EndingYear: "", Ongoing: false}, {Title: "Manager", CompanyName: "", StartingYear: "", EndingYear: "", Ongoing: false}, {Title: "Software Developer", CompanyName: "", StartingYear: "", EndingYear: "", Ongoing: false}, {Title: "Technical Lead", CompanyName: "", StartingYear: "", EndingYear: "", Ongoing: false}, {Title: "Software Consultant", CompanyName: "", StartingYear: "", EndingYear: "", Ongoing: false}, {Title: "Senior Software Developer", CompanyName: "", StartingYear: "", EndingYear: "", Ongoing: false}, {Title: "Assistant System Executive", CompanyName: "", StartingYear: "", EndingYear: "", Ongoing: false}}, Certifications: []string{}, BuilderVersion: "1.0.0", BuiltBy: "AI", FileUploadId: ""},
			{Name: "First Last", Email: "first.last@example.com", Phone: "+91 1234567890", City: "", State: "", Country: "", YoE: 11, TechSkills: []string{"C#", ".NET", ".NET core", "ASP.Net MVC", "Angular 9"}, SoftSkills: []string{"Good Communication", "Interpersonal Skills", "Flexibility", "Self-Motivation", "Team Player"}, RecommendedRoles: []string{"Sr. Technical lead", "Sr. Manager", "Sr. Software Engineer"}, Education: []model.Education{{Institute: "", Qualification: "B. E. Computer Engineering", CompletionYear: "2011"}, {Institute: "", Qualification: "Diploma in Computer Technology", CompletionYear: "2008"}}, Experience: []model.Experience{{Title: "Sr. Technical lead", CompanyName: "", StartingYear: "", EndingYear: "", Ongoing: true}, {Title: "Sr. Manager", CompanyName: "", StartingYear: "", EndingYear: "", Ongoing: false}, {Title: "Sr. Software Engineer", CompanyName: "", StartingYear: "", EndingYear: "", Ongoing: false}, {Title: "Technical Lead", CompanyName: "", StartingYear: "", EndingYear: "", Ongoing: false}, {Title: "Software Engineer", CompanyName: "", StartingYear: "", EndingYear: "", Ongoing: false}, {Title: "Software Developer", CompanyName: "", StartingYear: "", EndingYear: "", Ongoing: false}}, Certifications: []string{}, BuilderVersion: "1.0.0", BuiltBy: "AI", FileUploadId: ""},
			{Name: "First Last", Email: "first.last@example.com", Phone: "+91 1234567890", City: "Navi Mumbai", State: "", Country: "India", YoE: 17, TechSkills: []string{"C#.Net", "VB.Net", "jQuery", "JavaScript", "HTML5"}, SoftSkills: []string{"Organizational", "Communication", "Leadership", "Time Management", "Problem Solving"}, RecommendedRoles: []string{"Technical Architect", "Senior Consultant", "Technical Lead"}, Education: []model.Education{{Institute: "", Qualification: "Bachelor degree in Engineering", CompletionYear: "N/A"}}, Experience: []model.Experience{{Title: "Technical Architect", CompanyName: "Hexaware Technologies", StartingYear: "N/A", EndingYear: "Present", Ongoing: true}, {Title: "Senior Consultant", CompanyName: "Capgemini", StartingYear: "N/A", EndingYear: "N/A", Ongoing: false}, {Title: "Technical Lead", CompanyName: "Reliable Software Pvt. Ltd.", StartingYear: "N/A", EndingYear: "N/A", Ongoing: false}, {Title: "Technology Specialist", CompanyName: "PMAM IT Services Pvt. Ltd.", StartingYear: "N/A", EndingYear: "N/A", Ongoing: false}, {Title: "Software Eng.", CompanyName: "ShawMan Software Pvt. Ltd.", StartingYear: "N/A", EndingYear: "N/A", Ongoing: false}}, Certifications: []string{}, BuilderVersion: "1.0.0", BuiltBy: "AI", FileUploadId: ""},
			{Name: "First Last", Email: "first.last@example.com", Phone: "+91 1234567890", City: "", State: "", Country: "", YoE: 0, TechSkills: []string{"Go", "NodeJS", "Ruby on Rails", "Xcode", "ObjC"}, SoftSkills: []string{"Leadership", "Problem-solving", "Teamwork", "Communication", "Adaptability"}, RecommendedRoles: []string{"Senior Software Engineer", "Backend Developer", "iOS Developer"}, Education: []model.Education{{Institute: "Ramrao Adik Institute of Technology", Qualification: "B.E., Computer Engineering", CompletionYear: "2008"}, {Institute: "Ramnivas Ruia Junior College", Qualification: "HSC, Science", CompletionYear: "2004"}, {Institute: "St. John The Baptist High School", Qualification: "SSC", CompletionYear: "2002"}}, Experience: []model.Experience{{Title: "Senior Software Engineer", CompanyName: "Originate", StartingYear: "2013", EndingYear: "Present", Ongoing: true}, {Title: "Freelancer", CompanyName: "N/A", StartingYear: "2012", EndingYear: "2013", Ongoing: false}, {Title: "Senior Game Programmer", CompanyName: "Kreeda Games India", StartingYear: "2010", EndingYear: "2012", Ongoing: false}, {Title: "Flash Programmer", CompanyName: "Kreeda Games India", StartingYear: "2008", EndingYear: "2010", Ongoing: false}}, Certifications: []string(nil), BuilderVersion: "1.0.0", BuiltBy: "AI", FileUploadId: ""},
		}

		for i, testInput := range testInputs {
			openAiMockClient := openai.MockClientSuccess{
				Text: testInput,
			}
			persona, err := Build(testInput, &openAiMockClient)
			assert.NoError(t, err)

			var expectedOutput *model.Persona = nil

			if i < len(testExpectedOutputs) {
				expectedOutput = testExpectedOutputs[i]
			}

			assert.Equal(t, expectedOutput, persona)
		}
	})
}
